timeout: 1500s
steps:
  - name: node:12
    entrypoint: npm
    args: ["install"]
    dir: "web"
  - name: node:12
    entrypoint: npm
    args: ["run", "build"]
    dir: "web"
  - name: golang:1.16.5
    entrypoint: bash
    args:
      - "-c"
      - |
        mkdir -p /go/src/github.com/vikingo-project/vsat && cp -r . /go/src/github.com/vikingo-project/vsat && go env
    volumes:
      - name: go
        path: /go
  - name: golang:1.16.5
    dir: "/go/src/github.com/vikingo-project/vsat"
    args: ["go", "get", "-d"]
    env: ["GOPATH=/go", "GOOS=linux", "GOARCH=amd64"]
    volumes:
      - name: go
        path: /go
  - name: golang:1.16.5
    dir: "/go/src/github.com/vikingo-project/vsat"
    args: ["go", "get", "-u", "github.com/jteeuwen/go-bindata/..."]
    env: ["GOPATH=/go", "GOOS=linux", "GOARCH=amd64", "GO111MODULE=off"] # disable GO111MODULE! it's loading another version of bindata
    volumes:
      - name: go
        path: /go
  - name: golang:1.16.5
    dir: "/go/src/github.com/vikingo-project/vsat/web"
    args:
      [
        "/go/bin/go-bindata",
        "-pkg",
        "ctrl",
        "-o",
        "../ctrl/static.go",
        "dist/...",
      ]
    env: ["GOPATH=/go", "GOOS=linux", "GOARCH=amd64"]
    volumes:
      - name: go
        path: /go

  - name: golang:1.16.5
    dir: "/go/src/github.com/vikingo-project/vsat"
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        set -x && \
        go build -ldflags="-X 'github.com/vikingo-project/vsat/shared.Version=13.3.7' " -o vsat64
    env: ["GOPATH=/go", "GOOS=linux", "GOARCH=amd64", "CGO_ENABLED=0"]
    volumes:
      - name: go
        path: /go

  # Docker
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker login --username=$_DOCKERUSER --password=$_DOCKERPASS"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "vkngo/vsat:dev", "."]
    dir: "/go/src/github.com/vikingo-project/vsat"
    volumes:
      - name: go
        path: /go

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "vkngo/vsat:dev"]
    dir: "/go/src/github.com/vikingo-project/vsat"
