// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function About() {
  return window['go']['api']['APIC']['About']();
}

export function FileTypes() {
  return window['go']['api']['APIC']['FileTypes']();
}

export function Files(arg1) {
  return window['go']['api']['APIC']['Files'](arg1);
}

export function GetManager() {
  return window['go']['api']['APIC']['GetManager']();
}

export function Modules() {
  return window['go']['api']['APIC']['Modules']();
}

export function Networks() {
  return window['go']['api']['APIC']['Networks']();
}

export function Services(arg1) {
  return window['go']['api']['APIC']['Services'](arg1);
}

export function SessionEvents(arg1) {
  return window['go']['api']['APIC']['SessionEvents'](arg1);
}

export function Sessions(arg1) {
  return window['go']['api']['APIC']['Sessions'](arg1);
}
